import Book from '#models/book'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class BookSeeder extends BaseSeeder {
    public async run() {
        await Book.createMany([
            // --- THE CORE NOVELS (Oliver Bowden & others) ---
            { title: "Renaissance", author: "Oliver Bowden", publishedYear: 2009, genre: "Historical Fiction", summary: "The story of Ezio Auditore.", isbn: "978-0141046303", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/d5/AC_Renaissance_Cover.jpg", isAvailable: true, numberOfPages: 490, language: "English", publisher: "Penguin" },
            { title: "Brotherhood", author: "Oliver Bowden", publishedYear: 2010, genre: "Historical Fiction", summary: "Ezio's struggle in Rome.", isbn: "978-0441020355", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/5/52/AC_Brotherhood_Cover.jpg", isAvailable: true, numberOfPages: 528, language: "English", publisher: "Penguin" },
            { title: "The Secret Crusade", author: "Oliver Bowden", publishedYear: 2011, genre: "Historical Fiction", summary: "The life of Altaïr.", isbn: "978-0241951729", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/3/30/AC_The_Secret_Crusade_Cover.jpg", isAvailable: true, numberOfPages: 464, language: "English", publisher: "Penguin" },
            { title: "Revelations", author: "Oliver Bowden", publishedYear: 2011, genre: "Historical Fiction", summary: "Ezio's final journey.", isbn: "978-0241951743", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/2/29/AC_Revelations_Cover.jpg", isAvailable: true, numberOfPages: 528, language: "English", publisher: "Penguin" },
            { title: "Forsaken", author: "Oliver Bowden", publishedYear: 2012, genre: "Historical Fiction", summary: "The journal of Haytham Kenway.", isbn: "978-0241951736", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/6/62/AC_Forsaken_Cover.jpg", isAvailable: true, numberOfPages: 496, language: "English", publisher: "Penguin" },
            { title: "Black Flag", author: "Oliver Bowden", publishedYear: 2013, genre: "Historical Fiction", summary: "Edward Kenway's pirate life.", isbn: "978-0718178154", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/e/e0/AC_Black_Flag_Cover.jpg", isAvailable: true, numberOfPages: 464, language: "English", publisher: "Penguin" },
            { title: "Unity", author: "Oliver Bowden", publishedYear: 2014, genre: "Historical Fiction", summary: "Elise's side of the Revolution.", isbn: "978-0425279731", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/3/3b/AC_Unity_Cover.jpg", isAvailable: true, numberOfPages: 448, language: "English", publisher: "Penguin" },
            { title: "Underworld", author: "Oliver Bowden", publishedYear: 2015, genre: "Historical Fiction", summary: "The prequel to Syndicate.", isbn: "978-1101988183", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/bd/AC_Underworld_Cover.jpg", isAvailable: true, numberOfPages: 448, language: "English", publisher: "Penguin" },
            { title: "Desert Oath", author: "Oliver Bowden", publishedYear: 2017, genre: "Historical Fiction", summary: "The prequel to Origins.", isbn: "978-1405931731", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/8/87/AC_Desert_Oath_Cover.jpg", isAvailable: true, numberOfPages: 448, language: "English", publisher: "Penguin" },
            { title: "Odyssey", author: "Gordon Doherty", publishedYear: 2018, genre: "Historical Fiction", summary: "The official novelization.", isbn: "978-1405939737", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/9/90/AC_Odyssey_Cover.jpg", isAvailable: true, numberOfPages: 464, language: "English", publisher: "Penguin" },
            { title: "Geirmund's Saga", author: "Matthew J. Kirby", publishedYear: 2020, genre: "Historical Fiction", summary: "A Valhalla story.", isbn: "978-1945714443", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/3/3f/Geirmund%27s_Saga_Cover.jpg", isAvailable: true, numberOfPages: 368, language: "English", publisher: "Ubisoft" },

            // --- STANDALONE & FRAGMENTS ---
            { title: "Heresy", author: "Christie Golden", publishedYear: 2016, genre: "Sci-Fi/History", summary: "Simon Hathaway and Joan of Arc.", isbn: "978-1945289026", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/1/1b/AC_Heresy_Cover.jpg", isAvailable: true, numberOfPages: 384, language: "English", publisher: "Ubisoft" },
            { title: "The Ming Storm", author: "Yan Leisheng", publishedYear: 2021, genre: "Historical Fiction", summary: "Shao Jun in China.", isbn: "978-1800318465", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/5/52/AC_The_Ming_Storm_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "The Desert of Night", author: "Yan Leisheng", publishedYear: 2022, genre: "Historical Fiction", summary: "Shao Jun's second journey.", isbn: "978-1800318496", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/6/67/AC_The_Desert_of_Night_Cover.png", isAvailable: true, numberOfPages: 336, language: "English", publisher: "Aconyte" },
            { title: "The Witches of Edo", author: "Adrien Tomas", publishedYear: 2021, genre: "Historical Fiction", summary: "Fragments: Japan.", isbn: "978-2324028687", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/f/f6/AC_The_Witches_of_Edo_Cover.png", isAvailable: true, numberOfPages: 320, language: "English", publisher: "Ubisoft" },
            { title: "Children of Highlands", author: "Alain Puysségur", publishedYear: 2022, genre: "Historical Fiction", summary: "Fragments: Scotland.", isbn: "978-2324030116", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/a/ab/AC_The_Children_of_the_Highlands_Cover.png", isAvailable: true, numberOfPages: 310, language: "English", publisher: "Ubisoft" },
            { title: "The Barbarian Knight", author: "Olivier Gay", publishedYear: 2023, genre: "Historical Fiction", summary: "Fragments: Rome.", isbn: "978-2324031649", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/df/AC_The_Barbarian_Knight_Cover.png", isAvailable: true, numberOfPages: 300, language: "English", publisher: "Ubisoft" },

            // --- THE LAST DESCENDANTS ---
            { title: "Last Descendants", author: "Matthew J. Kirby", publishedYear: 2016, genre: "YA Fiction", summary: "Animus for teens.", isbn: "978-0545855518", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/a/a2/Last_Descendants_Cover.jpg", isAvailable: true, numberOfPages: 320, language: "English", publisher: "Scholastic" },
            { title: "Tomb of the Khan", author: "Matthew J. Kirby", publishedYear: 2016, genre: "YA Fiction", summary: "Search for the Trident.", isbn: "978-0545855532", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/a/a5/Tomb_of_the_Khan_Cover.jpg", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Scholastic" },
            { title: "Fate of the Gods", author: "Matthew J. Kirby", publishedYear: 2017, genre: "YA Fiction", summary: "Viking-age battle.", isbn: "978-0545855556", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/c/c5/Fate_of_the_Gods_Cover.jpg", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Scholastic" },

            // --- NEW ACONYTE NOVELS & MORE ---
            { title: "The Golden City", author: "Jaleigh Johnson", publishedYear: 2023, genre: "Historical Fiction", summary: "Basim in Constantinople.", isbn: "978-1803318465", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/4/4c/AC_The_Golden_City_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "Sword of White Horse", author: "Elsa Sjunneson", publishedYear: 2022, genre: "Historical Fiction", summary: "Hytham and Niamh.", isbn: "978-1800318533", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/3/30/Sword_of_the_White_Horse_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "The Magus Conspiracy", author: "Kate Heartfield", publishedYear: 2022, genre: "Historical Fiction", summary: "London 1851.", isbn: "978-1800318519", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/bd/The_Magus_Conspiracy_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "The Resurrection Plot", author: "Kate Heartfield", publishedYear: 2023, genre: "Historical Fiction", summary: "Sequel to Magus Conspiracy.", isbn: "978-1803318519", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/6/67/The_Resurrection_Plot_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "Daughter of No One", author: "Maria Lewis", publishedYear: 2024, genre: "Historical Fiction", summary: "Origins of the Hidden Ones.", isbn: "978-1803318526", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/df/Daughter_of_No_One_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },

            // (Repeat/Variation entries to reach 40 for testing purposes)
            { title: "Blade of Shao Jun 1", author: "Minoji Kurata", publishedYear: 2020, genre: "Manga", summary: "Graphic novelization.", isbn: "978-1974721474", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/a/a2/Blade_of_Shao_Jun_Vol_1.jpg", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Blade of Shao Jun 2", author: "Minoji Kurata", publishedYear: 2021, genre: "Manga", summary: "Graphic novelization Part 2.", isbn: "978-1974723041", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/b3/Blade_of_Shao_Jun_Vol_2.jpg", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Blade of Shao Jun 3", author: "Minoji Kurata", publishedYear: 2021, genre: "Manga", summary: "Graphic novelization Part 3.", isbn: "978-1974725472", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/c/c5/Blade_of_Shao_Jun_Vol_3.jpg", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Blade of Shao Jun 4", author: "Minoji Kurata", publishedYear: 2022, genre: "Manga", summary: "Graphic novelization Part 4.", isbn: "978-1974728565", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/e/ef/Blade_of_Shao_Jun_Vol_4.jpg", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Valhalla: Blood Brothers", author: "Feng Zi Su", publishedYear: 2021, genre: "Manhua", summary: "Viking brothers saga.", isbn: "978-1427867629", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/df/Blood_Brothers_Cover.jpg", isAvailable: true, numberOfPages: 192, language: "English", publisher: "Tokyopop" },
            { title: "Valhalla: Song of Glory", author: "Cavan Scott", publishedYear: 2021, genre: "Graphic Novel", summary: "Eivor and Sigurd.", isbn: "978-1506719269", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/5/52/Song_of_Glory_Cover.jpg", isAvailable: true, numberOfPages: 72, language: "English", publisher: "Dark Horse" },
            { title: "Conspiracies 1", author: "Guillaume Dorison", publishedYear: 2018, genre: "Graphic Novel", summary: "WWII Assassins.", isbn: "978-1785868245", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/bd/Conspiracies_Die_Glocke_Cover.jpg", isAvailable: true, numberOfPages: 48, language: "English", publisher: "Titan Comics" },
            { title: "Bloodstone 1", author: "Guillaume Dorison", publishedYear: 2019, genre: "Graphic Novel", summary: "Vietnam War story.", isbn: "978-1787733473", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/6/67/Bloodstone_Cover_1.jpg", isAvailable: true, numberOfPages: 48, language: "English", publisher: "Titan Comics" },
            { title: "Assassin's Creed 1", author: "Ian Edginton", publishedYear: 2015, genre: "Graphic Novel", summary: "Charlotte de la Cruz saga.", isbn: "978-1785850974", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/a/a2/AC_Comic_Issue_1_Cover.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Templars 1", author: "Fred Van Lente", publishedYear: 2016, genre: "Graphic Novel", summary: "The Templar side.", isbn: "978-1785854293", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/b3/AC_Templars_Issue_1_Cover.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Locus", author: "Ian Edginton", publishedYear: 2016, genre: "Graphic Novel", summary: "Syndicate tie-in.", isbn: "978-1785860263", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/c/c5/AC_Locus_Cover.jpg", isAvailable: true, numberOfPages: 112, language: "English", publisher: "Titan" },
            { title: "Reflections", author: "Ian Edginton", publishedYear: 2017, genre: "Graphic Novel", summary: "Legacy of the Assassins.", isbn: "978-1785862212", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/e/ef/AC_Reflections_Cover.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Origins: Comic", author: "Anthony Del Col", publishedYear: 2018, genre: "Graphic Novel", summary: "Aftermath of Origins.", isbn: "978-1785868665", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/df/AC_Origins_Comic_Cover.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Uprising 1", author: "Alex Paknadel", publishedYear: 2017, genre: "Graphic Novel", summary: "The Phoenix Project finale.", isbn: "978-1785857140", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/5/52/AC_Uprising_Cover.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Abstergo Employee Manual", author: "Christie Golden", publishedYear: 2016, genre: "Reference", summary: "Internal Templar document.", isbn: "978-1608879557", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/a/ab/AC_Movie_Manual_Cover.jpg", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Insight" }
        ])
    }
}