import Book from '#models/book'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class BookSeeder extends BaseSeeder {
    public async run() {
        await Book.createMany([
            // --- THE CORE NOVELS (Oliver Bowden & others) ---
            { title: "Renaissance", author: "Oliver Bowden", publishedYear: 2009, genre: "Historical Fiction", summary: "Renaissance Italy is a time of beauty and culture, but also of corruption and murder. When Ezio Auditore’s family is betrayed, he embarks on an epic quest for vengeance. To eradicate the corruption and restore his family's honor, he will learn the art of the Assassins, uncovering a grand conspiracy that stretches back centuries.", isbn: "978-0141046303", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/1/18/Renaissance.jpg", isAvailable: true, numberOfPages: 490, language: "English", publisher: "Penguin" , gameId: 2 },
            { title: "Brotherhood", author: "Oliver Bowden", publishedYear: 2010, genre: "Historical Fiction", summary: "Rome was once mighty, now it lies in ruins. The city is suffering under the tyrannical rule of the Borgia family, and only one man can free it from their golden shackles—Ezio Auditore, the Master Assassin. To defeat his enemies, Ezio must recruit and train a new generation of Assassins to fight by his side.", isbn: "978-0441020355", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/5/56/Assassin%27sCreedBrotherhoodnovel.jpg", isAvailable: true, numberOfPages: 528, language: "English", publisher: "Penguin" , gameId: 3 },
            { title: "The Secret Crusade", author: "Oliver Bowden", publishedYear: 2011, genre: "Historical Fiction", summary: "Niccolò Polo, father of Marco, will finally reveal the story he has kept secret all his life—the story of Altaïr, one of the Brotherhood’s most extraordinary Assassins. Altaïr embarks on a formidable mission—one which takes him throughout the Holy Land and shows him the true meaning of the Assassin’s Creed.", isbn: "978-0241951729", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/1/1b/The_Secret_Crusade_-_cover.jpg", isAvailable: true, numberOfPages: 464, language: "English", publisher: "Penguin" , gameId: 1 },
            { title: "Revelations", author: "Oliver Bowden", publishedYear: 2011, genre: "Historical Fiction", summary: "Older, wiser, and more lethal than ever, Master Assassin Ezio Auditore embarks on a final journey in the footsteps of his legendary mentor, Altaïr. In Constantinople, the heart of the Ottoman Empire, a growing army of Templars threatens to destabilize the region, and Ezio must find the keys to unlock the secrets of the Brotherhood's past.", isbn: "978-0241951743", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/d6/ACEzioAuditoreTheThirdChapter.jpg", isAvailable: true, numberOfPages: 528, language: "English", publisher: "Penguin" , gameId: 4 },
            { title: "Forsaken", author: "Oliver Bowden", publishedYear: 2012, genre: "Historical Fiction", summary: "The American Revolution is brewing. In a world of shifting alliances and hidden agendas, Haytham Kenway, the son of a pirate, travels to the New World on a mission for the Templar Order. This is his personal journal, revealing the truth behind the man who would become the Assassins' greatest adversary.", isbn: "978-0241951736", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/9/95/InlineACIII_Forsaken_Book_C.jpg", isAvailable: true, numberOfPages: 496, language: "English", publisher: "Penguin" , gameId: 5 },
            { title: "Black Flag", author: "Oliver Bowden", publishedYear: 2013, genre: "Historical Fiction", summary: "It is the Golden Age of Piracy. Edward Kenway, a brash young privateer, is drawn into the ancient war between Assassins and Templars. His quest for gold and glory will lead him across the Caribbean, from the pirate havens of Nassau to the opulent streets of Havana, as he searches for a legendary Observatory.", isbn: "978-0718178154", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/6/66/AC4_Black_Flag_roman.jpg/revision/latest?cb=20130604195847&path-prefix=fr", isAvailable: true, numberOfPages: 464, language: "English", publisher: "Penguin" , gameId: 6 },
            { title: "Unity", author: "Oliver Bowden", publishedYear: 2014, genre: "Historical Fiction", summary: "1789: Magnificent Paris basks in the twilight of the Enlightenment. Within the city, the French Revolution is igniting. As the people rise against the aristocracy, a young woman named Élise de la Serre is determined to find her father's killer, leading her into an uneasy alliance with the Assassin Arno Dorian.", isbn: "978-0425279731", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/4/48/Unity_novel.jpg", isAvailable: true, numberOfPages: 448, language: "English", publisher: "Penguin" , gameId: 8 },
            { title: "Underworld", author: "Oliver Bowden", publishedYear: 2015, genre: "Historical Fiction", summary: "A disgraced Assassin. A deep-cover agent. A city on the brink of change. In 1862, London is at the height of the Industrial Revolution. Henry Green, an Assassin from India, must navigate the dangerous underworld of the Victorian capital to pave the way for the Frye twins and dismantle the Templar grip on the city.", isbn: "978-1101988183", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/b1/AC_Underworld.jpg", isAvailable: true, numberOfPages: 448, language: "English", publisher: "Penguin" , gameId: 9 },
            { title: "Desert Oath", author: "Oliver Bowden", publishedYear: 2017, genre: "Historical Fiction", summary: "Before the Brotherhood, there was a father and a son. In 70 BC Egypt, a young Bayek follows in his father's footsteps as a Medjay—a protector of the people. Embarking on a journey across the Nile, he must face a shadowy conspiracy that threatens the very foundations of his home and his future.", isbn: "978-1405931731", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/e/ee/Desert_oath.jpg/revision/latest?cb=20191106131500", isAvailable: true, numberOfPages: 448, language: "English", publisher: "Penguin" , gameId: 10 },
            { title: "Odyssey", author: "Gordon Doherty", publishedYear: 2018, genre: "Historical Fiction", summary: "Ancient Greece, 431 BC. Kassandra, a mercenary of Spartan blood, is sentenced to death by her family. Surviving her execution, she embarks on an epic journey to discover the truth about her past and her destiny, becoming a legendary hero in a world torn apart by the Peloponnesian War.", isbn: "978-1405939737", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/7/73/AC_OD_novel.jpg", isAvailable: true, numberOfPages: 464, language: "English", publisher: "Penguin" , gameId: 11 },
            { title: "Geirmund's Saga", author: "Matthew J. Kirby", publishedYear: 2020, genre: "Historical Fiction", summary: "The mid-ninth century AD. The Viking invasion of England is imminent. Geirmund Hel-hide, a noble warrior of Viking blood, sets out to prove his worth and find his place in a world of shifting loyalties and ancient mysteries, eventually finding himself embroiled in the secret war of the Hidden Ones.", isbn: "978-1945714443", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/1/1c/ACVGS_cover.jpg/revision/latest?cb=20201002173402", isAvailable: true, numberOfPages: 368, language: "English", publisher: "Ubisoft" },

            // --- STANDALONE & FRAGMENTS ---
            { title: "Heresy", author: "Christie Golden", publishedYear: 2016, genre: "Sci-Fi/History", summary: "Simon Hathaway, a member of the Templar Inner Sanctum and new head of Abstergo's Historical Research Division, enters the Animus to relive the memories of his ancestor, Gabriel Laxart. He hopes to find evidence of a legendary artifact used by Joan of Arc, but instead finds a truth that challenges everything he believes.", isbn: "978-1945289026", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/4/40/Assassin%27s_Creed_Heresy_final_cover.jpg", isAvailable: true, numberOfPages: 384, language: "English", publisher: "Ubisoft" },
            { title: "The Ming Storm", author: "Yan Leisheng", publishedYear: 2021, genre: "Historical Fiction", summary: "China, 1526. The Ming Dynasty is in turmoil. Shao Jun, the last remaining Assassin of the Chinese Brotherhood, returns to her homeland seeking vengeance against the Eight Tigers—a powerful group of Templars who annihilated her peers. Trained by Ezio Auditore, she is a lethal force for justice.", isbn: "978-1800318465", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/7/75/AC_Ming_Storm_English_cover.jpg", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "The Desert of Night", author: "Yan Leisheng", publishedYear: 2022, genre: "Historical Fiction", summary: "Following the events of 'The Ming Storm', Shao Jun travels to the western frontiers of the Empire. In the vast deserts and ancient cities along the Silk Road, she must confront new Templar threats and uncover the secrets of the Precursors to ensure the survival of the Brotherhood in the East.", isbn: "978-1800318496", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/7/7a/AC_The_Desert_Threat_English_Cover.jpg/revision/latest/scale-to-width-down/1000?cb=20220601145900", isAvailable: true, numberOfPages: 336, language: "English", publisher: "Aconyte" },
            { title: "The Witches of Edo", author: "Adrien Tomas", publishedYear: 2021, genre: "Historical Fiction", summary: "Japan, 1868. The Tokugawa Shogunate is collapsing, and the Meiji Restoration is beginning. A young woman named Atsuko, trained in the ways of the Assassins, must navigate the shifting tides of history and a supernatural conspiracy known as the 'Witches of Edo' to protect her people.", isbn: "978-2324028687", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/c/c0/AC_Fragments_The_Witches_of_the_Moors.jpg/revision/latest/scale-to-width-down/1000?cb=20230319192747", isAvailable: true, numberOfPages: 320, language: "English", publisher: "Ubisoft" },
            { title: "Children of Highlands", author: "Alain Puysségur", publishedYear: 2022, genre: "Historical Fiction", summary: "Scotland, 1296. As the Wars of Scottish Independence begin, two siblings, Fillan and Aileas, are caught in the crossfire. When they discover their connection to the Brotherhood, they must fight to protect their heritage and their land from the encroaching shadow of the Templar-backed English forces.", isbn: "978-2324030116", coverImageUrl: "https://m.media-amazon.com/images/I/71BuSVqB14L._SY466_.jpg", isAvailable: true, numberOfPages: 310, language: "English", publisher: "Ubisoft" },

            // --- THE LAST DESCENDANTS ---
            { title: "Last Descendants", author: "Matthew J. Kirby", publishedYear: 2016, genre: "YA Fiction", summary: "When Owen’s father died in prison, accused of a crime he didn’t commit, Owen’s world fell apart. Now, he has the chance to clear his father’s name using the Animus. But Owen and his friends soon find themselves caught in a dangerous race for an ancient Piece of Eden—the Trident of Eden.", isbn: "978-0545855518", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/be/ACLD_Last_Descendants_cover.jpg/revision/latest?cb=20161106095624&path-prefix=fr", isAvailable: true, numberOfPages: 320, language: "English", publisher: "Scholastic" },
            { title: "Tomb of the Khan", author: "Matthew J. Kirby", publishedYear: 2016, genre: "YA Fiction", summary: "The search for the Trident of Eden continues. Owen and his friends travel to China to relive the memories of their ancestors during the Mongol Empire. As they delve deeper into the past, the lines between history and the present begin to blur, and the danger reaches a breaking point.", isbn: "978-0545855532", coverImageUrl: "https://covers.openlibrary.org/b/isbn/9780545855532-L.jpg", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Scholastic" },
            { title: "Fate of the Gods", author: "Matthew J. Kirby", publishedYear: 2017, genre: "YA Fiction", summary: "The final piece of the Trident of Eden is hidden in the Viking age. Owen and the other teens must travel back to the time of the Great Heathen Army to stop the Templars from changing the course of history. In a world of gods and warriors, they must make an impossible choice to save the future.", isbn: "978-0545855556", coverImageUrl: "https://m.media-amazon.com/images/I/71ZfAbXy2PL._SY466_.jpg", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Scholastic" },

            // --- NEW ACONYTE NOVELS & MORE ---
            { title: "The Golden City", author: "Jaleigh Johnson", publishedYear: 2023, genre: "Historical Fiction", summary: "Constantinople, 867 AD. Basim Ibn Ishaq, a master of the Hidden Ones, is tasked with investigating a mysterious plot within the heart of the Abbasid Caliphate. In the Golden City, he must use all his skills to navigate the shadows and protect the secrets of the Brotherhood from a new and deadly threat.", isbn: "978-1803318465", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/7/76/AC_The_Golden_City_Cover.png", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" , gameId: 13 },
            { title: "Sword of White Horse", author: "Elsa Sjunneson", publishedYear: 2022, genre: "Historical Fiction", summary: "Following the events of 'Geirmund's Saga', the Hidden One Hytham travels to the Isle of Skye. Accompanied by the warrior Niamh, he must find a legendary weapon—the Sword of the White Horse—before it falls into the hands of those who would use its power to sow chaos across the British Isles.", isbn: "978-1800318533", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/9/97/ACV_SotWH_English_cover.jpg/revision/latest?cb=20211121014253", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" , gameId: 12 },
            { title: "The Magus Conspiracy", author: "Kate Heartfield", publishedYear: 2022, genre: "Historical Fiction", summary: "London, 1851. The Great Exhibition is about to open, showcasing the wonders of the world. But behind the scenes, a secret war is being fought. Pierrette, an acrobat, and Simeon, a soldier, are drawn into a web of intrigue involving the Assassins, the Templars, and a mysterious group known as the Magus.", isbn: "978-1800318519", coverImageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSDe72DLAxty5uDh7-Mpf2MsbUKvSud2GnUpgLppZE3CpNw8k6p", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "The Resurrection Plot", author: "Kate Heartfield", publishedYear: 2023, genre: "Historical Fiction", summary: "Ten years after the events of 'The Magus Conspiracy', Pierrette and Simeon are once again called into action. A new threat has emerged, one that promises to bring the dead back to life and change the world forever. From the streets of London to the mountains of Europe, they must race against time to stop the Resurrection Plot.", isbn: "978-1803318519", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/b/bf/AC_Couverture_The_Resurrection_Plot.jpeg/revision/latest?cb=20230403205433&path-prefix=fr", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" },
            { title: "Daughter of No One", author: "Maria Lewis", publishedYear: 2024, genre: "Historical Fiction", summary: "In the aftermath of the Roman invasion of Egypt, a young woman named Roshan joins the Hidden Ones. Trained by the legendary Bayek and Aya, she must learn to navigate the dangerous world of political intrigue and ancient secrets to protect the innocent and ensure the survival of the Brotherhood.", isbn: "978-1803318526", coverImageUrl: "https://m.media-amazon.com/images/I/91iEEX0ndfL._SX342_.jpg", isAvailable: true, numberOfPages: 352, language: "English", publisher: "Aconyte" , gameId: 10 },

            // (Repeat/Variation entries to reach 40 for testing purposes)
            { title: "Blade of Shao Jun 1", author: "Minoji Kurata", publishedYear: 2020, genre: "Manga", summary: "A lethal manga adaptation of Shao Jun's quest for vengeance in 16th-century China. Following her training with Ezio Auditore, Shao Jun returns to her homeland to eliminate the Eight Tigers, a group of powerful Templars who slaughtered her peers and took control of the imperial court.", isbn: "978-1974721474", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/8/8e/ACBoSJ_Couverture_g%C3%A9n%C3%A9rique.jpeg/revision/latest?cb=20221211101510&path-prefix=fr", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Blade of Shao Jun 2", author: "Minoji Kurata", publishedYear: 2021, genre: "Manga", summary: "The saga continues as Shao Jun's mission to dismantle the Eight Tigers intensifies. As she navigates the treacherous politics of the Forbidden City, she must confront her past and use her unique skills to stay one step ahead of the Templar conspiracy that threatens to consume all of China.", isbn: "978-1974723041", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/4/40/ACBoSJ_Tome_2_couverture_FR.jpg/revision/latest?cb=20210328094042&path-prefix=fr", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Blade of Shao Jun 3", author: "Minoji Kurata", publishedYear: 2021, genre: "Manga", summary: "With the Eight Tigers cornered, Shao Jun must face her most dangerous adversary yet. The war between the Assassins and the Templars reaches a bloody climax in the heart of the Ming Empire, with the fate of millions hanging in the balance of a single blade.", isbn: "978-1974725472", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/d2/ACBoSJ_T3.jpg/revision/latest?cb=20210418105405&path-prefix=fr", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Blade of Shao Jun 4", author: "Minoji Kurata", publishedYear: 2022, genre: "Manga", summary: "The final chapter of Shao Jun's journey. As the dust settles on the ruins of the Tigers' influence, Shao Jun must ensure that the Brotherhood’s light continues to shine in the East. But even in victory, the shadow of the Templars remains, waiting for its next chance to strike.", isbn: "978-1974728565", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/d6/ACBoSJ_Couverture_Tome_4.jpg/revision/latest?cb=20220109193849&path-prefix=fr", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Viz Media" },
            { title: "Valhalla: Blood Brothers", author: "Feng Zi Su", publishedYear: 2021, genre: "Manhua", summary: "Two brothers, Ulf and Bjorn, follow Ivarr the Boneless to England in search of glory and land. But as they become embroiled in the wars of the Northmen, they discover that the greatest threat may not be the Saxons, but the secrets hidden within their own lineage and the ancient conflict that haunts the land.", isbn: "978-1427867629", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/d7/AC_Valhalla_manhua_English.jpg/revision/latest?cb=20231001023602", isAvailable: true, numberOfPages: 192, language: "English", publisher: "Tokyopop" , gameId: 12 },
            { title: "Valhalla: Song of Glory", author: "Cavan Scott", publishedYear: 2021, genre: "Graphic Novel", summary: "Years before Eivor's journey to England, she and her brother Sigurd must embark on a dangerous mission to reclaim a lost family treasure. From the frozen fjords of Norway to the dark forests of the North, they will face monsters, warriors, and the first hints of the ancient order that will define their future.", isbn: "978-1506719269", coverImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk7H8MwNHymplEK7bRlXIlPwqDqX1affwjzGop122ilTMBtAo5", isAvailable: true, numberOfPages: 72, language: "English", publisher: "Dark Horse" , gameId: 12 },
            { title: "Conspiracies 1", author: "Guillaume Dorison", publishedYear: 2018, genre: "Graphic Novel", summary: "At the height of World War II, a new Assassin named Eddie Gorm finds himself caught in a race to develop the world's first atomic weapon. From the laboratory of the Templars to the battlefields of Europe, he must influence the course of history before the shadow of the Order consumes the world.", isbn: "978-1785868245", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/6/6e/AC_Conspiracies_vol_1.jpg", isAvailable: true, numberOfPages: 48, language: "English", publisher: "Titan Comics" },
            { title: "Bloodstone 1", author: "Guillaume Dorison", publishedYear: 2019, genre: "Graphic Novel", summary: "In the jungles of Vietnam, a modern-day Assassin relives the memories of an ancestor during the height of the conflict. He soon discovers a hidden truth about the war—and a weapon of incredible power that the Templars have been searching for for decades.", isbn: "978-1787733473", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/5/5b/AC_Bloodstone_French_Comics_Cover.jpg", isAvailable: true, numberOfPages: 48, language: "English", publisher: "Titan Comics" },
            { title: "Assassin's Creed 1", author: "Ian Edginton", publishedYear: 2015, genre: "Graphic Novel", summary: "Charlotte de la Cruz, a modern-day banker, is recruited by the Assassins to find a legendary artifact. Using the Animus, she travels back to the Salem witch trials, where her ancestor must navigate a world of paranoia and religious fervor to protect the innocent from a Templar conspiracy.", isbn: "978-1785850974", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/9/96/Assassins_Creed_1_CoverA-1-1.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Templars 1", author: "Fred Van Lente", publishedYear: 2016, genre: "Graphic Novel", summary: "A rare look inside the Templar Order. Set in 1927 Shanghai, a high-ranking Templar must navigate the shifting alliances of the city while searching for an artifact of incredible power. This is the story of the men and women who believe that order is more important than freedom.", isbn: "978-1785854293", coverImageUrl: "https://m.media-amazon.com/images/I/71pcAO0yo-L._SY466_.jpg", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Locus", author: "Ian Edginton", publishedYear: 2016, genre: "Graphic Novel", summary: "A tie-in to 'Last Descendants' and 'Syndicate'. Tommy Greyling, a Victorian Pinkerton agent, is tasked with investigating a mysterious plot in London. Alongside the Assassin Henry Green, he must stop a group of Templars from using a Piece of Eden to control the British Empire.", isbn: "978-1785860263", coverImageUrl: "https://m.media-amazon.com/images/I/516CSXByo5L._SY445_SX342_ML2_.jpg", isAvailable: true, numberOfPages: 112, language: "English", publisher: "Titan" , gameId: 9 },
            { title: "Reflections", author: "Ian Edginton", publishedYear: 2017, genre: "Graphic Novel", summary: "Otso Berg, a high-ranking Templar, uses the Animus to study the lives of the Brotherhood's most legendary Assassins—Altaïr, Ezio, Connor, and Edward. He hopes to find their weaknesses, but instead discovers the enduring legacy of the Creed and the strength of the human spirit.", isbn: "978-1785862212", coverImageUrl: "https://books.google.fr/books/publisher/content?id=OXgrDwAAQBAJ&hl=fr&pg=PA1&img=1&zoom=3&sig=ACfU3U1oGsymB8drZ7HmiEfe-0dg22OZAw&w=1280", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Origins: Comic", author: "Anthony Del Col", publishedYear: 2018, genre: "Graphic Novel", summary: "The aftermath of Bayek's journey in Egypt. As the Hidden Ones begin to expand their influence across the Roman Republic, they must face new enemies and old betrayals. Aya (Amunet) travels to Rome to directly confront the shadow of the Order in the heart of the empire.", isbn: "978-1785868665", coverImageUrl: "https://static.wikia.nocookie.net/assassinscreed/images/d/d9/ACO_comics_compilation_-_couv_1.jpg/revision/latest?cb=20210130145527&path-prefix=fr", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" , gameId: 10 },
            { title: "Uprising 1", author: "Alex Paknadel", publishedYear: 2017, genre: "Graphic Novel", summary: "The epic conclusion to the Phoenix Project. The Assassins and Templars must form an uneasy alliance to stop the return of Juno and the rise of the Instruments of the First Will. The fate of the world hangs in the balance as two ancient foes fight for the future of humanity.", isbn: "978-1785857140", coverImageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTIRO1QJLyWSc19MA4TKk79SlrhjsGte-GDPnWT5Ne6ul5QlL0_", isAvailable: true, numberOfPages: 128, language: "English", publisher: "Titan" },
            { title: "Abstergo Employee Manual", author: "Christie Golden", publishedYear: 2016, genre: "Reference", summary: "An essential internal document for any prospective Abstergo Industries employee. This manual provides a deep dive into the corporate culture, technological advancements, and the hidden history of the Templar Order, offering an unprecedented look inside the world’s most powerful corporation.", isbn: "978-1608879557", coverImageUrl: "https://m.media-amazon.com/images/I/71ceGusIyQL._SY342_.jpg", isAvailable: true, numberOfPages: 160, language: "English", publisher: "Insight" }
        ])
    }
}