/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GameSchema extends BaseModel {
  static $columns = ['createdAt', 'desription', 'era', 'id', 'releaseDate', 'title', 'updatedAt'] as const
  $columns = GameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare desription: string
  @column()
  declare era: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare releaseDate: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
