/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookSchema extends BaseModel {
  static $columns = ['author', 'coverImageUrl', 'createdAt', 'genre', 'id', 'isAvailable', 'isbn', 'language', 'numberOfPages', 'publishedYear', 'publisher', 'summary', 'title', 'updatedAt'] as const
  $columns = BookSchema.$columns
  @column()
  declare author: string
  @column()
  declare coverImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare genre: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAvailable: boolean
  @column()
  declare isbn: string | null
  @column()
  declare language: string
  @column()
  declare numberOfPages: number
  @column()
  declare publishedYear: number
  @column()
  declare publisher: string
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CharacterSchema extends BaseModel {
  static $columns = ['affiliation', 'bannerImageUrl', 'bio', 'createdAt', 'gameId', 'id', 'imageUrl', 'isPlayable', 'name', 'updatedAt'] as const
  $columns = CharacterSchema.$columns
  @column()
  declare affiliation: string | null
  @column()
  declare bannerImageUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isPlayable: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameSchema extends BaseModel {
  static $columns = ['bannerImageUrl', 'createdAt', 'description', 'developer', 'era', 'id', 'imageUrl', 'platforms', 'publisher', 'releaseDate', 'title', 'updatedAt'] as const
  $columns = GameSchema.$columns
  @column()
  declare bannerImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare developer: string | null
  @column()
  declare era: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare platforms: string | null
  @column()
  declare publisher: string | null
  @column.date()
  declare releaseDate: DateTime
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'threadId', 'updatedAt', 'userId'] as const
  $columns = PostSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare threadId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ThreadSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'title', 'updatedAt', 'userId'] as const
  $columns = ThreadSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
